add dialog subcommand and refactor

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,9 +4,17 @@ FPREFIX="=====>"
 PREFIX="----->"
 INDENT="      "
 
-REPOSITORY="https://github.com/swarmlet/swarmlet.git"
-DEPENDENCIES=(acl curl git apt-transport-https apache2-utils moreutils)
+SWARMLET_REPO="https://github.com/swarmlet/swarmlet.git"
 SWARMLET_INSTALL_ROOT="/opt/swarmlet"
+
+if [[ $EUID -ne 0 ]]; then
+  if [[ $(dpkg-query -s sudo) ]]; then
+    echo "$PREFIX User is not root, using sudo"
+    export SUDO="sudo"
+  else 
+    echo "$PREFIX [ERROR] Please install sudo or run installer as root" && exit 1
+  fi
+fi
 
 if [ "${BASH_VERSINFO:-0}" -lt 4 ]; then
   echo "$PREFIX [ERROR] Unmet requirements: Bash 4"
@@ -16,149 +24,43 @@ if [ "${BASH_VERSINFO:-0}" -lt 4 ]; then
 fi
 
 declare -A DEFAULT_OPTS=(
-  [INTERACTIVE_INSTALL]=true    # (default true) Use CLI wizard to setup Swarmlet
-  [INSTALLATION_MODE]=full      # (default full, options: full|minimal|custom)
-  [ROOT_DOMAIN]=$HOSTNAME       # (default $HOSTNAME) The domain to use for deployment of included services
-  [INSTALL_BRANCH]=master       # (default master) The default branch to install
-  [CREATE_SWAP]=false           # (default false) Allocate 1GB of swap space
-  [INSTALL_ZSH]=false           # (default false) Install 'Oh My Zsh'
-  [NOOP]=                       # no-op for testing purposes
-  # > TODO/FIX:
-  # [DEBUG]=                    # (default undefined) Run installation in debug mode
+  [INSTALLATION_TYPE]=interactive  # (default interactive, options: interactive|noninteractive) Use CLI wizard to setup Swarmlet
+  [INSTALLATION_MODE]=full         # (default full, options: full|minimal|.. TODO)
+  [ROOT_DOMAIN]=$HOSTNAME          # (default $HOSTNAME) The domain to use for deployment of included services
+  [INSTALL_BRANCH]=master          # (default master) The default branch to install
+  [INSTALL_DOCKER]=true            # (default true) Install Docker and Docker Compose (recommended)
+  [INSTALL_MODULES]=               # (default undefined, options: matomo|swarmpit|swarmprom|portainer) Seperate by comma to install multiple modules
+  [CREATE_SWAP]=false              # (default false) Allocate 1GB of swap space
+  [INSTALL_ZSH]=false              # (default false) Install 'Oh My Zsh'
+  [NOOP]=                          # no-op for testing purposes
+  # > TODO:
+  # [DEBUG]=                       # (default undefined) Run installation in debug mode
 )
-
-# Set default environment variables
-for KEY in "${!DEFAULT_OPTS[@]}"; do
-  [ ! -z "${DEFAULT_OPTS[$KEY]}" ] && export "$KEY=${DEFAULT_OPTS[$KEY]}";
-done
-
-# Set environment variables from arguments if given
-shopt -s extglob
-while [[ "$#" > 0 ]]; do case "${1%=*}" in
-  @($(echo ${!DEFAULT_OPTS[@]} | sed 's/ /|/g'))) export "$1"; shift ;;
-  *) echo "Unknown argument: $1"; shift ;;
-esac; done
 
 set -eo pipefail; [[ $DEBUG ]] && set -x
 
-# TODO: unfinished business
-# Set environment variables interactively using the CLI wizard
-if [[ "$INTERACTIVE_INSTALL" == "true" ]]; then
-  # Set whiptail color scheme and dialog constants
-  export NEWT_COLORS="window=blue"
-  TTY_SIZE=$(stty size 2>/dev/null || echo 20 80)
-  TTY_ROWS=$(echo ${TTY_SIZE} | awk '{print $1}')
-  TTY_COLS=$(echo ${TTY_SIZE} | awk '{print $2}')
-
-  # Welcome message
-  SECTION_TITLE="Swarmlet installation wizard"
-  MESSAGE="\nWelcome to the Swarmlet interactive installation.\n\n\
-Installing Swarmlet $SWARMLET_VERSION\n\n\
-System:\n\
-$(bash --version | head -n 1)\n\
-$(uname -v | awk '{print $1}') $(uname) $(uname -r) $(uname -m)"
-  whiptail \
-    --title "$SECTION_TITLE" \
-    --msgbox "$MESSAGE" \
-    "$TTY_ROWS" "$TTY_COLS"
-
-  # Set the root domain name
-  SECTION_TITLE="Domain name configuration"
-  MESSAGE="\nEnter the domain name you want to use with Swarmlet.\n\n\
-Dashboards modules such as Traefik and Matomo will be hosted on subdomains of this domain.\n\
-Access the Traefik dashboard at https://traefik.yourdomain.com for example."
-  ROOT_DOMAIN=$(whiptail \
-    --title "$SECTION_TITLE" \
-    --inputbox "$MESSAGE" \
-    "$TTY_ROWS" "$TTY_COLS" \
-    "yourdomain.com" \
-    3>&1 1>&2 2>&3)
-  EXIT_STATUS=$?; [[ "$EXIT_STATUS" == "1" ]] && exit 1
-
-  # Set the installation mode
-  SECTION_TITLE="Installation mode"
-  MESSAGE="\nChoose the installation mode:"
-  INSTALLATION_MODE_OPTIONS=(
-    full "Full installation"
-    minimal "Minimal installation"
-    custom "Custom installation"
-  )
-  INSTALLATION_MODE=$(whiptail \
-    --title "$SECTION_TITLE" \
-    --menu "$MESSAGE" \
-    "$TTY_ROWS" "$TTY_COLS" "$((${#INSTALLATION_MODE_OPTIONS[@]} / 2))" \
-    "${INSTALLATION_MODE_OPTIONS[@]}" \
-    3>&1 1>&2 2>&3)
-  EXIT_STATUS=$?; [[ "$EXIT_STATUS" == "1" ]] && exit 1
-
-  # if [[ "$INSTALLATION_MODE" != "custom" ]]; then continue; fi
-  
-  # Set modules to install
-  SECTION_TITLE="Install modules"
-  MESSAGE="\nChoose which included modules to install.\n\
-All modules are self-hosted and open-source.\n\n\
-Press 'SPACE' to (de)select a module."
-  INSTALL_MODULES_OPTIONS=(
-    matomo "Install Matomo - Self-hosted analytics" on
-    swarmpit "Install Swarmpit - Swarm management" on
-    portainer "Install Portainer - Alternative to Swarmpit" off
-    swarmprom "Install Swarmprom - Swarm metrics and analytics" off
-  )
-  INSTALL_MODULES=$(whiptail \
-    --title "$SECTION_TITLE" \
-    --checklist "$MESSAGE" \
-    "$TTY_ROWS" "$TTY_COLS" "$((${#INSTALL_MODULES_OPTIONS[@]} / 3))" \
-    "${INSTALL_MODULES_OPTIONS[@]}" \
-    3>&1 1>&2 2>&3)
-  EXIT_STATUS=$?; [[ "$EXIT_STATUS" == "1" ]] && exit 1
-
-  # Add swap space
-  SECTION_TITLE="Optional: Add swap space"
-  MESSAGE="\nCreate 1GB of swap space?\n\n\
-Memory installed: $(free -m  | grep Mem | awk '{print $2}') MB\n\
-Available memory: $(free -m  | grep Mem | awk '{print $4}') MB\n\n\
-If you've selected Swarmprom, consider adding some swap if you have less than 2GB of RAM."
-  CREATE_SWAP_OPTIONS=(
-    true "Allocate 1GB of swap space"
-    false "Skip this step"
-  )
-  CREATE_SWAP=$(whiptail \
-    --title "$SECTION_TITLE" \
-    --menu "$MESSAGE" \
-    "$TTY_ROWS" "$TTY_COLS" "$((${#CREATE_SWAP_OPTIONS[@]} / 2))" \
-    "${CREATE_SWAP_OPTIONS[@]}" \
-    3>&1 1>&2 2>&3)
-  EXIT_STATUS=$?; [[ "$EXIT_STATUS" == "1" ]] && exit 1
-
-  # Install zsh
-  SECTION_TITLE="Optional: Install zsh"
-  MESSAGE="\nInstall Zsh and Oh My Zsh?"
-  INSTALL_ZSH_OPTIONS=(
-    true "Install Zsh and Oh My Zsh"
-    false "Skip this step"
-  )
-  INSTALL_ZSH=$(whiptail \
-    --title "$SECTION_TITLE" \
-    --menu "$MESSAGE" \
-    "$TTY_ROWS" "$TTY_COLS" "$((${#INSTALL_ZSH_OPTIONS[@]} / 2))" \
-    "${INSTALL_ZSH_OPTIONS[@]}" \
-    3>&1 1>&2 2>&3)
-  EXIT_STATUS=$?; [[ "$EXIT_STATUS" == "1" ]] && exit 1
-fi
-
 install() {
-  echo "$PREFIX Installing Swarmlet"
-  echo "$PREFIX Installing dependencies"
-  apt-get update -y -qq >/dev/null
-  apt-get install -y -qq "${DEPENDENCIES[@]}"
+  echo "$FPREFIX Installing Swarmlet"
 
-  echo "$PREFIX Installing Docker and Docker Compose"
-  wget -nv -O - https://get.docker.com/ | sh >/dev/null
-  curl -fsSL "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-  chmod +x /usr/local/bin/docker-compose
+  # Set default environment variables
+  for KEY in "${!DEFAULT_OPTS[@]}"; do
+    [[ ! -z "${DEFAULT_OPTS[$KEY]}" ]] && export "$KEY=${DEFAULT_OPTS[$KEY]}"
+  done
 
-  echo "$PREFIX Cloning $REPOSITORY"
-  git clone -q $REPOSITORY $SWARMLET_INSTALL_ROOT
+  # Set environment variables from arguments if given
+  shopt -s extglob
+  while [[ "$#" > 0 ]]; do case "${1%=*}" in
+    @($(echo ${!DEFAULT_OPTS[@]} | sed 's/ /|/g'))) export "$1"; shift ;;
+    *) echo "Unknown argument: $1"; shift ;;
+  esac; done
+
+  echo "$PREFIX Installing required packages"
+  # TODO: support other package managers
+  $SUDO apt-get update -y -qq &>/dev/null
+  $SUDO apt-get install -y -qq apt-transport-https git
+
+  echo "$PREFIX Cloning $SWARMLET_REPO"
+  git clone -q $SWARMLET_REPO $SWARMLET_INSTALL_ROOT
 
   if [[ "$INSTALL_BRANCH" != "master" ]]; then
     echo "$PREFIX Checking out $INSTALL_BRANCH"
@@ -167,18 +69,11 @@ install() {
     popd >/dev/null
   fi
 
-  if [[ "$INSTALL_ZSH" == "true" ]]; then
-    echo "$PREFIX Installing 'Oh My Zsh'"
-    apt-get install -y -qq zsh >/dev/null
-    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended >/dev/null
-    chsh -s $(which zsh)
-  fi
-
   echo "$PREFIX Linking executable"
   ln -s $SWARMLET_INSTALL_ROOT/swarmlet /usr/local/sbin/
 
   echo "$PREFIX Initializing Swarmlet"
-  swarmlet init "$@"
+  swarmlet init $INSTALLATION_TYPE "$@"
 
   echo "$FPREFIX Server initialized as manager node"
   swarmlet node ls
@@ -194,4 +89,4 @@ install() {
   echo "$INDENT $ docker service logs loadbalancer_traefik -f"
 }
 
-install
+install "$@"
diff --git a/src/functions b/src/functions
--- a/src/functions
+++ b/src/functions
@@ -1,5 +1,115 @@
 #!/usr/bin/env bash
 
+ensure-root() {
+  if [[ $EUID -ne 0 ]]; then
+    if [[ $(dpkg-query -s sudo) ]]; then
+      echo "$PREFIX User is not root, using sudo"
+      export SUDO="sudo"
+    else 
+      echo "$PREFIX [ERROR] Please install sudo or run as root" && exit 1
+    fi
+  fi
+}
+
+check-bash-version() {
+  if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
+    echo "$PREFIX [ERROR] Unmet requirements: Bash 4"
+    echo "$INDENT Your Bash version is $BASH_VERSION"
+    echo "$PREFIX Exiting with error code 1" 1>&2
+    exit 1
+  fi
+}
+
+check-swarmlet-version() {
+  pushd $SWARMLET_INSTALL_ROOT >/dev/null
+  git describe --match "v*" $INSTALL_BRANCH
+  popd >/dev/null
+}
+
+update-package-cache() {
+  # Check to see if apt-get update has already been run today
+  PKG_CACHE="/var/lib/apt/lists/"
+  UPDATE_PKG_CACHE="$PKG_MANAGER update"
+
+  TIMESTAMP=$(stat -c %Y $PKG_CACHE)
+  TIMESTAMP_AS_DATE=$(date -d @"$TIMESTAMP" "+%b %e")
+  TODAY=$(date "+%b %e")
+
+  if [ ! "$TODAY" == "$TIMESTAMP_AS_DATE" ]; then
+    echo -n "$PREFIX $PKG_MANAGER update has not been run today, updating"
+    $SUDO $UPDATE_PKG_CACHE &>/dev/null
+  fi
+}
+
+notify-package-updates-available() {
+  echo -n "$PREFIX Checking $PKG_MANAGER for upgraded packages"
+  PKG_COUNT="$PKG_MANAGER -s -o Debug::NoLocking=true upgrade | grep -c ^Inst || true"
+  UPDATES_TO_INSTALL=$(eval "$PKG_COUNT")
+  if [[ $UPDATES_TO_INSTALL -eq 0 ]]; then
+    echo "$PREFIX System up to date, continuing installation"
+  else
+    echo "$PREFIX There are $UPDATES_TO_INSTALL updates available"
+    # TODO: explain why and how to update
+    # echo "$PREFIX Please update your packages"
+  fi
+}
+
+pkg-check-and-install() {
+  PKG_INSTALL="$PKG_MANAGER --yes --no-install-recommends install"
+  dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -c "$1 installed" || $PKG_INSTALL "$1"
+}
+
+install-dependencies() {
+  echo "$PREFIX Installing dependencies"
+  DEPENDENCIES=$1
+  PKG_INSTALL="$PKG_MANAGER --yes --no-install-recommends install"
+
+  echo iptables-persistent iptables-persistent/autosave_v4 boolean true | $SUDO debconf-set-selections
+  echo iptables-persistent iptables-persistent/autosave_v6 boolean false | $SUDO debconf-set-selections
+
+  if command -v debconf-apt-progress &>/dev/null; then
+    $SUDO debconf-apt-progress -- $PKG_INSTALL "${DEPENDENCIES[@]}"
+  else
+    for PKG in "${DEPENDENCIES[@]}"; do
+      echo -n "$PREFIX Checking and installing $PKG"
+      $SUDO pkg-check-and-install $PKG &>/dev/null
+    done
+  fi
+}
+
+set-hostname() {
+  echo "$PREFIX Setting hostname"
+  NEW_HOSTNAME=$1
+
+  if command -v hostnamectl &>/dev/null; then
+    # Prefer hostnamectl, no restart required
+    hostnamectl set-hostname $NEW_HOSTNAME
+  else
+    # Fall back on manual hostname configuration, restart required
+    $SUDO echo $NEW_HOSTNAME >/etc/hostname && echo "you need to reboot for hostname changes to take effect"
+    $SUDO sed -i "s/127.0.1.1.*$NEW_HOSTNAME/127.0.1.1\t$ROOT_DOMAIN/g" /etc/hosts
+  fi
+}
+
+install-docker() {
+  echo "$PREFIX Installing Docker and Docker Compose"
+  wget -nv -O - https://get.docker.com/ | sh &>/dev/null
+  curl -fsSL "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+  chmod +x /usr/local/bin/docker-compose
+}
+
+install-zsh() {
+  echo "$PREFIX Installing 'Oh My Zsh'"
+  $SUDO apt-get install -y -qq zsh &>/dev/null
+  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended &>/dev/null
+  chsh -s $(which zsh)
+}
+
+abort-installation() {
+  echo "$PREFIX Aborting installation"
+  exit 1
+}
+
 check-docker() {
   systemctl show --property ActiveState docker | grep -q "ActiveState=active"
 }
@@ -26,21 +136,18 @@ git-local-push() {
 create-swap() {
   SIZE=${1:-1G}
   FILE_PATH=${2:-/swapfile}
-  sudo fallocate -l $SIZE $FILE_PATH
-  sudo chmod 600 $FILE_PATH
-  sudo mkswap $FILE_PATH
-  sudo swapon $FILE_PATH
-  echo "$FILE_PATH none swap sw 0 0" | sudo tee -a /etc/fstab
+  $SUDO fallocate -l $SIZE $FILE_PATH
+  $SUDO chmod 600 $FILE_PATH
+  $SUDO mkswap $FILE_PATH
+  $SUDO swapon $FILE_PATH
+  echo "$FILE_PATH none swap sw 0 0" | $SUDO tee -a /etc/fstab
 }
 
 uninstall-swarmlet() {
-  if [[ -d "$USER_ROOT" ]]; then
-    rm -rf /home/git
-    userdel git -f
-  fi
+  [[ -d "$USER_ROOT" ]] && rm -rf $USER_ROOT && userdel git -f
+  [[ -d "$REPO_ROOT" ]] && rm -rf $REPO_ROOT
+  [[ -d "$SWARMLET_ROOT" ]] && rm -rf $SWARMLET_ROOT
   [[ -f /usr/local/sbin/swarmlet ]] && unlink /usr/local/sbin/swarmlet
-  if [[ -d "$REPO_ROOT" ]]; then rm -rf $REPO_ROOT; fi
-  if [[ -d "$SWARMLET_ROOT" ]]; then rm -rf $SWARMLET_ROOT; fi
 }
 
 reinstall-swarmlet() {
@@ -48,7 +155,7 @@ reinstall-swarmlet() {
   curl -fsSL https://get.swarmlet.dev | bash
 }
 
-check_existing() {
+check-existing() {
 if  [[ -d "$USER_ROOT" ]] ||
     [[ -d "$REPO_ROOT" ]] ||
     [[ -f /usr/local/sbin/swarmlet ]] ||
@@ -59,31 +166,37 @@ if  [[ -d "$USER_ROOT" ]] ||
   fi
 }
 
-setup_ssh() {
-  if [[ ! -d ~/.ssh ]]; then
-    mkdir -p ~/.ssh/
-  fi
-
-  if [[ ! -f ~/.ssh/id_rsa.pub ]]; then
-    ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
-    echo "$INDENT Execute ssh-keygen --[done]"
-  fi
-
-  if [[ ! -f ~/.ssh/authorized_keys ]]; then
-    touch ~/.ssh/authorized_keys
-    echo "$INDENT Create ~/.ssh/authorized_keys --[done]"
-    chmod 700 ~/.ssh/authorized_keys
-    cat ~/.ssh/id_rsa.pub >>~/.ssh/authorized_keys
-    echo "$INDENT Append the public keys id_rsa into authorized keys --[done]"
-    chmod 400 ~/.ssh/authorized_keys
-    chmod 700 ~/.ssh/
+check-swarm() {
+  if [[ "$(docker info 2>/dev/null  | grep Swarm | sed 's/Swarm: //g')" == " active" ]]; then
+    return 1
+  else
+    return 0
   fi
 }
 
-check-swarm(){
-    if [[ "$(docker info 2>/dev/null  | grep Swarm | sed 's/Swarm: //g')" == " active" ]]; then
-        return 1
-    else
-        return 0
-    fi
+nuke() {
+  uninstall-swarmlet
+  $SUDO apt-get remove --purge docker docker-compose
+  $SUDO apt autoremove
 }
+
+# setup-ssh() {
+#   if [[ ! -d ~/.ssh ]]; then
+#     mkdir -p ~/.ssh/
+#   fi
+
+#   if [[ ! -f ~/.ssh/id_rsa.pub ]]; then
+#     ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
+#     echo "$INDENT Execute ssh-keygen --[done]"
+#   fi
+
+#   if [[ ! -f ~/.ssh/authorized_keys ]]; then
+#     touch ~/.ssh/authorized_keys
+#     echo "$INDENT Create ~/.ssh/authorized_keys --[done]"
+#     chmod 700 ~/.ssh/authorized_keys
+#     cat ~/.ssh/id_rsa.pub >>~/.ssh/authorized_keys
+#     echo "$INDENT Append the public keys id_rsa into authorized keys --[done]"
+#     chmod 400 ~/.ssh/authorized_keys
+#     chmod 700 ~/.ssh/
+#   fi
+# }
